---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age1wj5atxan7eayt64u27guyr7hataknz5r7w88cndqn2uc7g9u9atqzgeafp
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1wj5atxan7eayt64u27guyr7hataknz5r7w88cndqn2uc7g9u9atqzgeafp
