# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:u/4IOEoMrvnJy23YtKsB,iv:Y1u+LJm9G+RfFt8rBWGBbFz9jzZB2mYHjN0t7JBrQFE=,tag:U81MDNc2H2DJeHXZEc44og==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:qutmYbJi19PWPgm9I9WEnSiEd31x0BDO4DQ=,iv:RFJm5DaLmm+eJInS/nvW0PPrf62cBgxgaClwEJDHHU8=,tag:NoYVUS3pnVqv0itai/HKJA==,type:str]
    SECRET_NFS_SERVER: ENC[AES256_GCM,data:ranLK634O8Y38GFcQg==,iv:hovyOI8bVpIVqIjTYFB320wRunDhSS0WF8yw+HFLL6M=,tag:yu3o8+OTWs/f42BrQoQNnw==,type:str]
    SECRET_NFS_PATH: ENC[AES256_GCM,data:3M0Ef7Bbeyc3R5xIFBZLHted,iv:pJHun6vHFTyepKLIuKd0uqN3Tim/0aFZXEO1E9oJOqQ=,tag:0+uB3Bjocv4lEAHnoTdHsw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wj5atxan7eayt64u27guyr7hataknz5r7w88cndqn2uc7g9u9atqzgeafp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBaU1iUDE4cjEzc1dVYkkv
            ODU4KzRxaHRQUVFnMEcwMTUrZUFTM1NFMXdNCm1ZQm1wNGQyMWJwWUZ0OTQvVm11
            YlBrUWRlSnpSYzR5UWE3UFI0SlVHVEEKLS0tIEt5akM1Nm1XNUxWbDBJWGc2UnBZ
            TmFQSDhnRS91Umc5TlROa3FPakdta28KzRk4vDVJa5owzb7xIKmyBzWyR8sHayYk
            OD0GQgSlQ7UB4ig12zmrYNgmuMdOWR9qy+K6+eIVJ1MqNQZ/09dx1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-03T03:58:56Z"
    mac: ENC[AES256_GCM,data:9J2u3AGfFoA8cI3hreY7EDkyl/Wg/O+ZKOPd2OLRpdcexA+z72YZe+eAu5wBrpjnskRMJ4l/VkEhHrKoAEfa0jp+ubizzkNka/VPgQpmr8dCHSx+KRMyGKWkfrid4TCZPPMrchrtKjPNiNU/x7l5WEaACDEeLHiYMoNNN5XUjR4=,iv:GkN7CmCgJBtj96gBJpnhrPn5zHqoU8daXYLh/GF0t2M=,tag:vocpTplttb6OJb2hvsLSdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
