---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: nfs-provisioner
spec:
  interval: 15m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.16
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5

  values:
    storageClass:
      defaultClass: true
    nfs:
      server: ${SECRET_NFS_SERVER}
      path: ${SECRET_NFS_PATH}
      mountOptions:
        - nfsvers=4.2
        - tcp
        - intr
        - hard
        - noatime
        - nodiratime
        - rsize=1048576
        - wsize=1048576
